# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeRecord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unionId',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
